# Generated by Django 5.1.4 on 2025-01-07 09:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_user', '0001_initial'),
        ('lease', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leasemanagement',
            name='lease_frequency',
            field=models.CharField(choices=[('yearly', 'Yearly'), ('monthly', 'Monthly'), ('weekly', 'Weekly'), ('daily', 'Daily')], default='yearly', max_length=50),
        ),
        migrations.CreateModel(
            name='LeaseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('LEASE_AGREEMENT', 'Lease Agreement'), ('ADDENDUM', 'Lease Addendum'), ('INSPECTION', 'Property Inspection'), ('TERMINATION', 'Lease Termination'), ('OTHER', 'Other Document')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='lease_documents/')),
                ('description', models.TextField(blank=True)),
                ('is_signed', models.BooleanField(default=False)),
                ('signature_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='lease.leasemanagement')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_user.clientusers')),
            ],
        ),
        migrations.CreateModel(
            name='LeaseRenewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_start_date', models.DateField()),
                ('new_end_date', models.DateField()),
                ('new_monthly_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('response_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_renewals', to='client_user.clientusers')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='lease.leasemanagement')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_renewals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeaseTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pets_allowed', models.BooleanField(default=False)),
                ('pet_deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('utilities_included', models.BooleanField(default=False)),
                ('maintenance_terms', models.TextField()),
                ('parking_spots', models.IntegerField(default=0)),
                ('special_conditions', models.TextField(blank=True)),
                ('notice_period_days', models.IntegerField(default=30)),
                ('late_fee_percentage', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lease', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='lease.leasemanagement')),
            ],
        ),
    ]
