# Generated by Django 5.1.4 on 2025-01-07 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payee', models.CharField(help_text='The one who receives money from the payer', max_length=50)),
                ('fees_type', models.CharField(choices=[('Insurance', 'Insurance'), ('Legal', 'Legal'), ('Security', 'Security'), ('Sanitation', 'Sanitation'), ('Taxes', 'Taxes'), ('Water', 'Water'), ('Waste Disposal', 'Waste Disposal'), ('Utilities', 'Utilities')], default='Sanitation', max_length=25)),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Paid', max_length=25)),
                ('date', models.DateField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=20)),
                ('account_name', models.CharField(max_length=100)),
                ('swift_code', models.CharField(blank=True, max_length=11, null=True)),
                ('iban', models.CharField(blank=True, max_length=34, null=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fees_type', models.CharField(choices=[('General', 'General'), ('Security', 'Security'), ('Sanitation', 'Sanitation'), ('Water', 'Water'), ('Waste Disposal', 'Waste Disposal'), ('Utilities', 'Utilities')], default='Sanitation', max_length=25)),
                ('unit_name', models.CharField(blank=True, max_length=50, null=True)),
                ('property_unique_id', models.UUIDField()),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=25)),
                ('date', models.DateField(verbose_name='Date Due')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('payer', models.ForeignKey(help_text='The name of the one who pays money to the payee', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('property_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property.propertymodel')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('property_unique_id', models.UUIDField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('commission', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('depositor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_depositors', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_recipients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-payment_date',),
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.TextField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('bank_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment_track.bankdetail')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_recipients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-payment_date',),
            },
        ),
    ]
