# Generated by Django 4.2 on 2024-12-24 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 27, 13, 9, 45, 253468, tzinfo=datetime.timezone.utc)),
        ),
    ]
