# Generated by Django 4.2 on 2024-12-23 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_feedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('property_manager', 'Property Manager'), ('accountant', 'Accountant'), ('leasing_agent', 'Leasing Agent'), ('maintenance_supervisor', 'Maintenance Supervisor'), ('maintenance_technician', 'Maintenance Technician')], default='', max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(help_text='The tenants this user belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientusers_set', to='core.client')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ClientUsers',
                'verbose_name_plural': 'ClientUsers',
            },
        ),
    ]
