# Generated by Django 4.2 on 2024-12-23 22:38

from django.db import migrations, models
import django.db.models.deletion
import property.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_user', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccommodationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AmenitiesModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InspectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('unit_id', models.CharField(max_length=100)),
                ('property_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('address', models.CharField(max_length=250)),
                ('country', models.CharField(blank=True, max_length=150, null=True)),
                ('state', models.CharField(blank=True, max_length=150, null=True)),
                ('city', models.CharField(blank=True, max_length=150, null=True)),
                ('no_of_total_units', models.PositiveIntegerField(default=1, verbose_name='Total Number Of Units')),
                ('no_of_available_units', models.PositiveIntegerField(default=1, verbose_name='Total Number of Available Units')),
                ('list_property', models.BooleanField(default=False, help_text='Do you want to list this property?')),
                ('is_verified', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager', to='client_user.clientusers')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('unit_number', models.CharField(max_length=50)),
                ('taken', models.BooleanField(default=False)),
                ('tenant_id', models.CharField(blank=True, max_length=50, null=True)),
                ('price_per_year', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('list_property', models.BooleanField(default=False, help_text='Do you want to list this unit?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accommodation_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accommodation_type', to='property.accommodationtype')),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='property.propertymodel')),
            ],
        ),
        migrations.CreateModel(
            name='UnitListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=320, null=True, verbose_name='Description')),
                ('no_of_baths', models.IntegerField(default=0, verbose_name='No Of Baths')),
                ('vid_file', models.FileField(blank=True, null=True, upload_to='BuildingInterior/video/flat', verbose_name='Video File')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('features', models.ManyToManyField(help_text='You can select more than one.', to='property.amenitiesmodels')),
                ('unit_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='unit_listing', to='property.unit')),
            ],
        ),
        migrations.AddField(
            model_name='propertymodel',
            name='property_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_type', to='property.propertytype'),
        ),
        migrations.CreateModel(
            name='PropertyListingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_sale', models.BooleanField(default=False, verbose_name='For Sale')),
                ('collect_rent', models.BooleanField(default=True, verbose_name='Do you collect rent on the property or on behave of the property owner?')),
                ('allow_online_payment', models.BooleanField(default=True)),
                ('vid_file', models.FileField(blank=True, null=True, upload_to='BuildingExterior/video/building/', verbose_name='Video File')),
                ('is_newly_built', models.BooleanField(default=False, verbose_name='Newly Built')),
                ('description', models.TextField(blank=True, null=True)),
                ('has_electricity', models.BooleanField(default=True)),
                ('water', models.BooleanField(default=True)),
                ('property_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=11, null=True)),
                ('tenant_agreement', models.FileField(blank=True, default=property.models.get_default_file, null=True, upload_to='documents/TAs/', verbose_name='Tenant Agreement')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('features', models.ManyToManyField(help_text='You can select more than one.', to='property.amenitiesmodels')),
                ('property_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='property.propertymodel')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/')),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['content_type', 'object_id'], name='property_im_content_bc7cae_idx'),
        ),
    ]
